# ------------------------- #
# Don't Remove Credit 
# Ask Doubt @AU_Bot_Discussion 
# Owner @Mr_Mohammed_29 
# ------------------------- #
services:
  - type: web
    name: au-filter-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 bot.py"
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: ADMINS
        sync: false

# ------------------------- #
# Don't Remove Credit 
# Ask Doubt @AU_Bot_Discussion 
# Owner @Mr_Mohammed_29 
# ------------------------- #
